// <auto-generated />
using Love4AnimalsApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Love4Animals.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260430230229_AddPublicationsDonationsComments")]
    partial class AddPublicationsDonationsComments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Love4AnimalsApi.Models.Campaign", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("GoalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Campaigns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Campaña para rescatar animales silvestres",
                            GoalAmount = 5000m,
                            Title = "Rescate de fauna"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Campaña para reunir alimento",
                            GoalAmount = 3000m,
                            Title = "Alimento para refugio"
                        });
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Donations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500m,
                            CampaignId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 300m,
                            CampaignId = 2,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Shares")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Publications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Ayuda a los animales silvestres de nuestra región",
                            ImageUrl = "https://example.com/img1.jpg",
                            Likes = 0,
                            Shares = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "Campaña de alimento para el refugio local",
                            ImageUrl = "https://example.com/img2.jpg",
                            Likes = 0,
                            Shares = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.PublicationCampaign", b =>
                {
                    b.Property<int>("PublicationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CampaignId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PublicationId", "CampaignId");

                    b.HasIndex("CampaignId");

                    b.ToTable("PublicationCampaigns");

                    b.HasData(
                        new
                        {
                            PublicationId = 1,
                            CampaignId = 1
                        },
                        new
                        {
                            PublicationId = 2,
                            CampaignId = 2
                        });
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Animal rescue volunteer",
                            Email = "jairo@gmail.com",
                            Name = "Jairo",
                            Phone = "+1234567890",
                            UserType = "Missionary"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Passionate about animal welfare",
                            Email = "maria@gmail.com",
                            Name = "Maria",
                            Phone = "+0987654321",
                            UserType = "Donor"
                        });
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.Comment", b =>
                {
                    b.HasOne("Love4AnimalsApi.Models.Publication", "Publication")
                        .WithMany("Comments")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.PublicationCampaign", b =>
                {
                    b.HasOne("Love4AnimalsApi.Models.Campaign", "Campaign")
                        .WithMany()
                        .HasForeignKey("CampaignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Love4AnimalsApi.Models.Publication", "Publication")
                        .WithMany("PublicationCampaigns")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Campaign");

                    b.Navigation("Publication");
                });

            modelBuilder.Entity("Love4AnimalsApi.Models.Publication", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("PublicationCampaigns");
                });
#pragma warning restore 612, 618
        }
    }
}
